providers = ["...", "timezone"]
[variables]
TZ = "Asia/Shanghai"
[phases.setup]
nixPkgs = ['python311']
[phases.install]
cmds = ['python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt']
[start]
cmd = "python ./main.py"
