providers = ['...', 'python']

[phases.setup]
    # Install dependencies
    script = '''
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    '''

[phases.install]

[start]
cmd = "source venv/bin/activate && python3 main.py"
